module.exports = {
  CLOUD_ENV: 'xinzhu-d7gtsc4pz7a9fa09b',
  MAX_FREE_PER_DAY: 10,
  RATE_LIMIT_SECONDS: 30,
  BLESSING_MIN_LENGTH: 50,
  BLESSING_MAX_LENGTH: 300,
  POSTER_WIDTH: 1080,
  POSTER_HEIGHT: 1920,
  FALLBACK_POSTER_BG: 'cloud://default-poster-bg.png',
  MSG_SEC_CHECK: true,
  TEMPERATURE_BASE: 0.85,
};
